### ISSUE TITLE
MotifComparer.get_all_scores() error

### ISSUE THREAD

**Issue by hschult** [vanheeringen-lab/gimmemotifs#243]
**Describe the bug**
Since I updated gimmemotifs to 0.17.0 the `get_all_scores` function of the `MotifComparer` no longer works.

**To Reproduce**
```
from gimmemotifs.motif import Motif
from gimmemotifs.comparison import MotifComparer

m1 = Motif(pfm=[[100, 100, 300, 500],
                [200, 300, 100, 300],
                [500, 300, 400, 200],
                [200, 300, 200,   0]
               ])
m1.id = "m1"

m2 = Motif(pfm=[[900, 800, 100,   0],
                [  0, 100, 400, 100],
                [100, 100, 500, 200],
                [  0,   0,   0, 700],
                [300, 100, 900, 500]
               ])
m2.id = "m2"

mc = MotifComparer()
mc.get_all_scores(motifs=[m1], dbmotifs=[m2], match="total", metric="pcc", combine="mean")
```

**Error**
```
ERROR:root:_get_all_scores failed
Traceback (most recent call last):
  File "/workspace/.conda/tobias-test/lib/python3.9/site-packages/gimmemotifs/comparison.py", line 164, in _get_all_scores
    scores[m1.id][m2.id] = mc.compare_motifs(
  File "/workspace/.conda/tobias-test/lib/python3.9/site-packages/gimmemotifs/comparison.py", line 461, in compare_motifs
    m1.wiggle_pwm(), m2.wiggle_pwm(), metric, combine
AttributeError: 'Motif' object has no attribute 'wiggle_pwm'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/.conda/tobias-test/lib/python3.9/site-packages/gimmemotifs/comparison.py", line 703, in get_all_scores
    for m1, v in result.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Installation information (please complete the following information):**
 - OS: Linux
 - Installation conda & pip (I tried both)
 - Version 0.17.0 (it worked with 0.16.0)

**Comment by siebrenf** [comment]
Your code example is great, thanks for that! 

I've created a pull request with (what I think to be) the fix. You can install it with `pip install git+https://github.com/vanheeringen-lab/gimmemotifs.git@wiggle`. Note that this PR is based on the develop branch, so it might contain some additional minor changes.

Alternatively, you can bypass this bug by using a different `metric`. the bugged metrics are "pcc" and "akl".

**Comment by msbentsen** [comment]
I work with @hschult, so thank you for the quick fix, @siebrenf! 

I can confirm that metrics "pcc" (which was the one we needed) and "akl" work again in `0.17.0+8.g79e3d3d`, as well as "seqcor" and "wic", but "chisq" fails with the same example above (but with another error):
```
Traceback (most recent call last):
  File "*gimmemotifs/comparison.py", line 164, in _get_all_scores
    scores[m1.id][m2.id] = mc.compare_motifs(
  File "*gimmemotifs/comparison.py", line 463, in compare_motifs
    return self.max_total(m1.pwm, m2.pwm, metric, combine)
  File "*gimmemotifs/comparison.py", line 591, in max_total
    s = self.score_matrices(p1, p2, metric, combine)
  File "*gimmemotifs/comparison.py", line 531, in score_matrices
    scores.append(func(pos1, pos2))
  File "*gimmemotifs/comparison.py", line 207, in chisq
    return chi2_contingency([p1, p2])[1]
  File "*scipy/stats/contingency.py", line 276, in chi2_contingency
    raise ValueError("The internally computed table of expected "
ValueError: The internally computed table of expected frequencies has a zero element at (0, 3).
Traceback (most recent call last):
  File "*", line 25, in <module>
    mc.get_all_scores(motifs=[m1], dbmotifs=[m2], match="total", metric="chisq", combine="mean")
  File "/*gimmemotifs/comparison.py", line 702, in get_all_scores
    for m1, v in result.items():
AttributeError: 'NoneType' object has no attribute 'items'
```
Not sure if this is a special case of the example motifs here though.

**Comment by siebrenf** [comment]
`scipy.stats.chi2_contingency` throws this error to prevent a divide by zero. This happens for every combination of zero-frequencies.

In your example, the error can be prevented by removing all rows with a zero element in one or both motifs. For example:
```python
m1 = Motif(pfm=[[100, 100, 300, 500],
                [200, 300, 100, 300],
                [500, 300, 400, 200],
                # [200, 300, 200,   0]
               ])
```

I have added a dumb try-except to the gimmemotifs function in the same pull request. This will simply add a tiny increment to the frequencies that threw an error.

**Comment by msbentsen** [comment]
Ah I see, makes sense, thank you! @hschult I guess we can close this?

**Comment by hschult** [comment]
Yeah, thanks a lot for your support!
